apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-dep

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

    spec:
      containers:
      - name: simple-pod

        image: yashmane108/simple-web:REPLACE

        ports:
        - containerPort: 80
